Restrict incorrect comparison order (#222)
* add ComparisonOrderViolation, WrongOrderVisitor

* add tests for ComparisonOrderViolation, Update CHANGELOG.md

* resolve merge conflict

* add ComparisonOrderViolation to Summary section

* add missing ',' to fix invalid syntax

* remove unnecessary variables

* add more testcases, modify WrongOrderVisitor logic

* refactor order.py

* fix NameError 'ast'

* fix parametrizing

* fix flake8 errors & parametrizing

* fix flake-8 errors, fix WrongOrderViolations, modify WronOrderVisitor logic

* refactor test_comparison_order.py

* add seperate test case for compund comparison

* fix flake-8 errors

* fix more flake-8 errors

* fix high jones complexity error

* fix F811 redefinition error

* fix F811 redefinition of unused 'test_consistent_chained_comparison'

* add test case for 'in'

* increase branch coverage

* increase branch coverage

* revert edited func call comparisons, add test cases for func call comparisons

* modify order.py logic

* refactor order.py

* fix flake-8 errors

* resolve Z202 Found too many module members

* Update tests/test_visitors/test_ast/test_general/test_comparison_order.py

* Fix E127 continuation line over-indented for visual indent

* Update tests/test_visitors/test_ast/test_general/test_comparison_order.py

* resolve Z202 Found too many module members

* Update wemake_python_styleguide/visitors/ast/order.py

* Revert "resolve Z202 Found too many module members"

This reverts commit 2ad986f71181deef1ff779aa3f02638c8f8ebc7c.

* resolve Z202 Found too many module members

* fix typing errors

* Update wemake_python_styleguide/visitors/ast/order.py